/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FTP_H_RPCGEN
#define	_FTP_H_RPCGEN

#include <rpc/rpc.h>
#ifndef _KERNEL
#include <synch.h>
#include <thread.h>
#endif /* !_KERNEL */

#ifdef __cplusplus
extern "C" {
#endif

#define	SUCCESS_OP 0
#define	NO_CATALOG_ERR 1
#define	NOT_EXIST_ERR 2
#define	ACCESS_DENIED_ERR 3
#define	MAX_SIZE 128
#define	MAX_LS_CONTENT 10240
#define	MAX_BINARY_FILE 10485760

struct file_info {
	char *path;
	char *file_name;
};
typedef struct file_info file_info;

struct catalog_state {
	char *content_view;
};
typedef struct catalog_state catalog_state;

struct file_content_info {
	struct {
		u_int data_len;
		char *data_val;
	} data;
	char *name;
};
typedef struct file_content_info file_content_info;

#define	FTP_PROG	0x33224358
#define	FTP_VERS	1

#if defined(__STDC__) || defined(__cplusplus)
#define	init	0
extern  enum clnt_stat init_1(void *, catalog_state *, CLIENT *);
extern  bool_t init_1_svc(void *, catalog_state *, struct svc_req *);
#define	cd	1
extern  enum clnt_stat cd_1(file_info *, int *, CLIENT *);
extern  bool_t cd_1_svc(file_info *, int *, struct svc_req *);
#define	ls	2
extern  enum clnt_stat ls_1(file_info *, catalog_state *, CLIENT *);
extern  bool_t ls_1_svc(file_info *, catalog_state *, struct svc_req *);
#define	scp	3
extern  enum clnt_stat scp_1(file_info *, int *, CLIENT *);
extern  bool_t scp_1_svc(file_info *, int *, struct svc_req *);
#define	wget	4
extern  enum clnt_stat wget_1(file_info *, int *, CLIENT *);
extern  bool_t wget_1_svc(file_info *, int *, struct svc_req *);
#define	get_file	5
extern  enum clnt_stat get_file_1(file_info *, file_content_info *, CLIENT *);
extern  bool_t get_file_1_svc(file_info *, file_content_info *, struct svc_req *);
#define	send_file	6
extern  enum clnt_stat send_file_1(file_content_info *, int *, CLIENT *);
extern  bool_t send_file_1_svc(file_content_info *, int *, struct svc_req *);
extern int ftp_prog_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define	init	0
extern  enum clnt_stat init_1();
extern  bool_t init_1_svc();
#define	cd	1
extern  enum clnt_stat cd_1();
extern  bool_t cd_1_svc();
#define	ls	2
extern  enum clnt_stat ls_1();
extern  bool_t ls_1_svc();
#define	scp	3
extern  enum clnt_stat scp_1();
extern  bool_t scp_1_svc();
#define	wget	4
extern  enum clnt_stat wget_1();
extern  bool_t wget_1_svc();
#define	get_file	5
extern  enum clnt_stat get_file_1();
extern  bool_t get_file_1_svc();
#define	send_file	6
extern  enum clnt_stat send_file_1();
extern  bool_t send_file_1_svc();
extern int ftp_prog_1_freeresult();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_file_info(XDR *, file_info*);
extern  bool_t xdr_catalog_state(XDR *, catalog_state*);
extern  bool_t xdr_file_content_info(XDR *, file_content_info*);

#else /* K&R C */
extern bool_t xdr_file_info();
extern bool_t xdr_catalog_state();
extern bool_t xdr_file_content_info();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FTP_H_RPCGEN */
