/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ftp.h"
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#include <signal.h>
#include <rpc/pmap_clnt.h> /* for pmap_unset */
#include <string.h> /* strcmp */
#include <unistd.h> /* setsid */
#include <sys/types.h>
#include <memory.h>
#include <stropts.h>
#include <netconfig.h>
#include <sys/resource.h> /* rlimit */
#include <syslog.h>

#ifndef SIG_PF
#define	SIG_PF void(*)(int)
#endif

#ifdef DEBUG
#define	RPC_SVC_FG
#endif

#define	_RPCSVC_CLOSEDOWN 120
static int _rpcpmstart;		/* Started by a port monitor ? */

/* States a server can be in wrt request */

#define	_IDLE 0
#define	_SERVED 1

static int _rpcsvcstate = _IDLE;	/* Set when a request is serviced */
static int _rpcsvccount = 0;		/* Number of requests being serviced */
mutex_t _svcstate_lock;			/* lock for _rpcsvcstate, _rpcsvccount */

static
void _msgout(char* msg)
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog(LOG_ERR, msg);
	else
		(void) fprintf(stderr, "%s\n", msg);
#else
	syslog(LOG_ERR, msg);
#endif
}

/*ARGSUSED*/
static void *
closedown(void *arg)
{
	/*CONSTCOND*/
	while (1) {
		(void) sleep(_RPCSVC_CLOSEDOWN/2);

		if (mutex_trylock(&_svcstate_lock) != 0)
			continue;

		if (_rpcsvcstate == _IDLE && _rpcsvccount == 0) {
			int size;
			int i, openfd = 0;

			size = svc_max_pollfd;
			for (i = 0; i < size && openfd < 2; i++)
				if (svc_pollfd[i].fd >= 0)
					openfd++;
			if (openfd <= 1)
				exit(0);
		} else
			_rpcsvcstate = _IDLE;

		mutex_unlock(&_svcstate_lock);
	}
}

static void
ftp_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		file_info cd_1_arg;
		file_info ls_1_arg;
		file_info scp_1_arg;
		file_info wget_1_arg;
		file_info get_file_1_arg;
		file_content_info send_file_1_arg;
	} argument;
	union {
		catalog_state init_1_res;
		int cd_1_res;
		catalog_state ls_1_res;
		int scp_1_res;
		int wget_1_res;
		file_content_info get_file_1_res;
		int send_file_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	mutex_lock(&_svcstate_lock);
	_rpcsvccount++;
	mutex_unlock(&_svcstate_lock);
	switch (rqstp->rq_proc) {
	case init:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_catalog_state;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))init_1_svc;
		break;

	case cd:
		_xdr_argument = (xdrproc_t) xdr_file_info;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))cd_1_svc;
		break;

	case ls:
		_xdr_argument = (xdrproc_t) xdr_file_info;
		_xdr_result = (xdrproc_t) xdr_catalog_state;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))ls_1_svc;
		break;

	case scp:
		_xdr_argument = (xdrproc_t) xdr_file_info;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))scp_1_svc;
		break;

	case wget:
		_xdr_argument = (xdrproc_t) xdr_file_info;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))wget_1_svc;
		break;

	case get_file:
		_xdr_argument = (xdrproc_t) xdr_file_info;
		_xdr_result = (xdrproc_t) xdr_file_content_info;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))get_file_1_svc;
		break;

	case send_file:
		_xdr_argument = (xdrproc_t) xdr_file_content_info;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))send_file_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		mutex_lock(&_svcstate_lock);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		mutex_unlock(&_svcstate_lock);
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		mutex_lock(&_svcstate_lock);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		mutex_unlock(&_svcstate_lock);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, _xdr_result, (char *)&result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, _xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	if (!ftp_prog_1_freeresult(transp, _xdr_result, (caddr_t) &result))
		_msgout("unable to free results");

	mutex_lock(&_svcstate_lock);
	_rpcsvccount--;
	_rpcsvcstate = _SERVED;
	mutex_unlock(&_svcstate_lock);
	return;
}

main()
{
	pid_t pid;
	int i;
	int mode = RPC_SVC_MT_AUTO;

	if (!rpc_control(RPC_SVC_MTMODE_SET, &mode)) {
		_msgout("unable to set automatic MT mode.");
		exit(1);
	}
	mutex_init(&_svcstate_lock, USYNC_THREAD, NULL);
	(void) sigset(SIGPIPE, SIG_IGN);

	/*
	 * If stdin looks like a TLI endpoint, we assume
	 * that we were started by a port monitor. If
	 * t_getstate fails with TBADF, this is not a
	 * TLI endpoint.
	 */
	if (t_getstate(0) != -1 || t_errno != TBADF) {
		char *netid;
		struct netconfig *nconf = NULL;
		SVCXPRT *transp;
		int pmclose;

		_rpcpmstart = 1;
		openlog("ftp", LOG_PID, LOG_DAEMON);

		if ((netid = getenv("NLSPROVIDER")) == NULL) {
		/* started from inetd */
			pmclose = 1;
		} else {
			if ((nconf = getnetconfigent(netid)) == NULL)
				_msgout("cannot get transport info");

			pmclose = (t_getstate(0) != T_DATAXFER);
		}
		if ((transp = svc_tli_create(0, nconf, NULL, 0, 0)) == NULL) {
			_msgout("cannot create server handle");
			exit(1);
		}
		if (nconf)
			freenetconfigent(nconf);
		if (!svc_reg(transp, FTP_PROG, FTP_VERS, ftp_prog_1, 0)) {
			_msgout("unable to register (FTP_PROG, FTP_VERS).");
			exit(1);
		}
		if (pmclose) {
			if (thr_create(NULL, 0, closedown, NULL,
					0, NULL) != 0) {
				_msgout("cannot create closedown thread");
				exit(1);
			}
		}
		svc_run();
		exit(1);
		/* NOTREACHED */
	}	else {
#ifndef RPC_SVC_FG
		int size;
		struct rlimit rl;
		pid = fork();
		if (pid < 0) {
			perror("cannot fork");
			exit(1);
		}
		if (pid)
			exit(0);
		rl.rlim_max = 0;
		getrlimit(RLIMIT_NOFILE, &rl);
		if ((size = rl.rlim_max) == 0)
			exit(1);
		for (i = 0; i < size; i++)
			(void) close(i);
		i = open("/dev/null", 2);
		(void) dup2(i, 1);
		(void) dup2(i, 2);
		setsid();
		openlog("ftp", LOG_PID, LOG_DAEMON);
#endif
	}
	if (!svc_create(ftp_prog_1, FTP_PROG, FTP_VERS, "netpath")) {
		_msgout("unable to create (FTP_PROG, FTP_VERS) for netpath.");
		exit(1);
	}

	svc_run();
	_msgout("svc_run returned");
	exit(1);
	/* NOTREACHED */
}
