/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ftp.h"

bool_t
xdr_file_info(register XDR *xdrs, file_info *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_string(xdrs, &objp->path, MAX_SIZE))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->file_name, MAX_SIZE))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_catalog_state(register XDR *xdrs, catalog_state *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_string(xdrs, &objp->content_view, MAX_LS_CONTENT))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_file_content_info(register XDR *xdrs, file_content_info *objp)
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->name, MAX_SIZE))
		return (FALSE);
	return (TRUE);
}
